version: 2.1
jobs:
  test-ui-unit:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
            - node-v1-{{ .Branch }}-
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
      - run:
          name: Install Dependencies
          command: cd ./FE/src && npm install
      - run:
          name: Unit test UI
          command: cd ./FE/src && npm run test:unit
      - run:
          name: Build UI
          command: cd ./FE/src && npm run build
      - run:
          name: Install Firebase Dependencies
          command: cd ./FE && npm install
      - run:
          name: Deploy App to Firebase
          command: cd ./FE && firebase deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-ui-unit
      - deploy-to-firebase:
          requires:
            - test-ui-unit

