version: 2.1

executors:
  node-12-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep

jobs:
  deploy-ui:
    executor: node-12-executor
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@6"
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
            - node-v1-{{ .Branch }}
      - run:
          name: INSTALL - App dependencies
          working_directory: ./FE/src
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
          paths:
            - ./FE/src/node_modules
      - run:
          name: Unit test UI
          working_directory: ./FE/src
          command: npm run test:unit
      - run:
          name: Build UI
          working_directory: ./FE/src
          command: npm run build
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "FE/functions/package.json" }}
            - node-v1-{{ .Branch }}
      - run:
          name: INSTALL - Function dependencies
          working_directory: ./FE/functions
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "FE/functions/package.json" }}
          paths:
            - ./FE/functions/node_modules
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "FE/package.json" }}
            - node-v1-{{ .Branch }}
      - run:
          name: INSTALL - Firebase dependencies
          working_directory: ./FE
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "FE/package.json" }}
          paths:
            - ./FE/node_modules
      - run:
          name: INSTALL - Firebase Dependencies
          working_directory: ./FE
          command: ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy-ui

