version: 2.1

executors:
  node-12-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep

commands:
  restore-save-cache:
    description: "Save and retore cache"
    parameters:
      checksumFile:
        type: string
      paths:
        type: string
      whichDeps:
        type: string
    steps:
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "<< parameters.checksumFile >>" }}
            - node-v1-{{ .Branch }}
      - run:
          name: INSTALL - << parameters.whichDeps >> dependencies
          working_directory: << parameters.paths >>
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "<< parameters.checksumFile >>" }}
          paths:
            - << parameters.paths >>/node_modules

jobs:
  deploy-ui:
    executor: node-12-executor
    steps:
      - checkout

      #--------
      # Install App dependencies
      #--------
      - restore-save-cache:
          checksumFile: FE/src/package.json
          paths: ./FE/src
          whichDeps: "App"
      
      #--------
      # Test App
      #--------
      - run:
          name: TEST - UI
          working_directory: ./FE/src
          command: npm run test:unit
      
      #--------
      # Build App
      #--------
      - run:
          name: BUILD - UI
          working_directory: ./FE/src
          command: npm run build
     
      #--------
      # Install cached function dependencies
      #--------
      - restore-save-cache:
          checksumFile: FE/functions/package.json
          paths: ./FE/functions
          whichDeps: "Functions"
      
      #--------
      # Install cached firebase dependencies
      #--------
      - restore-save-cache:
          checksumFile: FE/package.json
          paths: ./FE
          whichDeps: "Firebase"
      
      #--------
      # Deploy App
      #--------
      - run: |
          cd ./FE
          if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"
          else
              circleci-agent step halt
          fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy-ui

