version: 2.1
jobs:
  build:
    docker:
      - image: bitbucketpipelines/firebase-deploy
    working_directory: ~/sweep
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
     
