version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep
    steps:
      - checkout
      - run:
          name: clear npm mods
          command: rm -rf node_modules packkage-lock.json
      - run:
          name: Install Dependencies
          command: npm install
     
