version: 2.1

executors:
  node-12-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep

jobs:
  deploy-ui:
    executor: node-12-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
            - node-v1-{{ .Branch }}-
      - run:
          name: Install Dependencies
          command: cd ./FE/src && npm install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
      - run:
          name: Unit test UI
          command: cd ./FE/src && npm run test:unit
      - run:
          name: Build UI
          command: cd ./FE/src && npm run build
      - run:
          name: Install Firebase Dependencies and deploy
          command: cd ./FE && npm install && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy-ui

