version: 2.1

executors:
  node-12-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/sweep

jobs:
  test-ui:
    executor: node-12-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
            - node-v1-{{ .Branch }}
      - run:
          name: Install Dependencies
          command: cd ./FE/src && npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "FE/src/package.json" }}
          paths:
            - ./FE/src/node_modules
      - run:
          name: Unit test UI
          command: cd ./FE/src && npm run test:unit
      - run:
          name: Build UI
          command: cd ./FE/src && npm run build
      - run:
          name: Install function deps
          command: cd ./FE/functions && npm install
      - run:
          name: Install Firebase Dependencies
          command: cd ./FE && npm install && ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy-ui

