version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/sweep
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
     
